# Generated by Django 4.2.2 on 2023-06-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='reference',
            field=models.CharField(max_length=50, null=True, verbose_name='Reference'),
        ),
    ]
